baseurl = "https://iviguera.github.io/alpha-guide/"
title = "The Alpha's Guide to the Galaxy"
languageCode = "en-us"

theme = "hugo-theme-learn"
publishdir = "public"
builddrafts = true
canonifyurls = true

[params]
  menu = [
    "start",
    "rookie-fitting",
    "market",
    "career-agents",
    "upgrading-ships",
    "new-goals",
    "training",
    "corps",
    "learn-more",
    "reference"
  ]
  editURL = "https://github.com/iviguera/alpha-guide/edit/master/content/"
